apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_ta5nocnw7r6n:
            custom_fragment: ''
            directories:
                avd_tuoc5s6rnq3a:
                    allow_override:
                        - All
                    custom_fragment: ''
                    files_match:
                        avdfm_u4t1hhih98a1:
                            custom_fragment: ''
                            path: \.php$
                            provider: filesmatch
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    path: /var/www/silverstripe
                    provider: directory
                    require:
                        - 'all granted'
            docroot: /var/www/silverstripe
            port: '80'
            serveraliases:
                - www.silverstripe.dev
            servername: silverstripe.dev
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: ''
            ssl_certs_dir: ''
            ssl_chain: ''
            ssl_cipher: ''
            ssl_key: ''
            ssl_protocol: ''
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
cron:
    install: '1'
    jobs: {  }
drush:
    install: '0'
    version: 8.0.5
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_m6elmji8bo8y:
            name: es-01
firewall:
    install: '1'
    rules: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.log.file: /var/log/hhvm/error.log
        hhvm.log.use_log_file: '1'
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
    php_ini:
        date.timezone: UTC
        display_errors: 'On'
        error_reporting: '-1'
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_nffnkctgn0c7:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_jibh2rv0xczp:
            name: dbname
            sql: ''
    grants:
        mariadbng_vuvnq46asib1:
            privileges:
                - ALL
            table: '*.*'
            user: dbuser
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_jct3ayjzw8n7:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_9yddl3h3bkq8:
            name: dbname
            sql: ''
    grants:
        mysqlng_g4ihhjgb2fxk:
            privileges:
                - ALL
            table: '*.*'
            user: dbuser
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_dxfxumd5hedf:
            client_max_body_size: 1m
            index_files:
                - index.html
                - index.htm
                - index.php
            listen_port: '80'
            locations:
                nxvl_ebcxnlcs7nhd:
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    location: /
                    proxy: ''
                    proxy_redirect: ''
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                nxvl_g33hwn5os51t:
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    location: '~ \.php$'
                    proxy: ''
                    proxy_redirect: ''
                    set:
                        - '$path_info $fastcgi_path_info'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
            rewrite_to_https: '1'
            server_aliases:
                - www.awesome.dev
            server_name: awesome.dev
            spdy: '1'
            ssl: '0'
            ssl_cert: ''
            ssl_ciphers: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            www_root: /var/www/awesome
    proxies: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - xml
        pear: {  }
        pecl: {  }
    ini:
        date.timezone: UTC
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_vd8w6o9ymszt:
            ini:
                group: www-data
                listen: '127.0.0.1:9000'
                prefix: www
                security.limit_extensions: .php
                user: www-user
    composer: '1'
    composer_home: ''
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
python:
    install: '1'
    packages: {  }
    versions: {  }
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
redis:
    install: '0'
    settings:
        port: '6379'
ruby:
    install: '1'
    versions:
        rv_443aj3e6jxbh:
            bundler: '1'
            default: '1'
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
            version: 2.3.1
server:
    install: '1'
    packages: {  }
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_foipiaykwdrx:
                        cpus: '2'
                        hostname: silverstripedev.host
                        id: silverstripedev
                        memory: '1024'
                        network:
                            forwarded_port:
                                vflmnfp_oybizn0ms96l:
                                    guest: '22'
                                    host: '9648'
                            private_network: 192.168.56.101
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_mtc87azfjbh0:
                group: www-data
                owner: www-data
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    auto: 'true'
                    exclude:
                        - .vagrant/
                        - .git/
                smb:
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                    smb_host: ''
                    smb_password: ''
                    smb_username: ''
                source: ./
                sync_type: default
                target: /var/www
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
wpcli:
    install: '0'
    version: v0.24.1
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'

